#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace A0161_SQL_Server_Porc_UnitTest
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UnitTest")]
	public partial class MySerialNumberDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertmy_serial_number(my_serial_number instance);
    partial void Updatemy_serial_number(my_serial_number instance);
    partial void Deletemy_serial_number(my_serial_number instance);
    #endregion
		
		public MySerialNumberDataContext() :
        base(global::A0161_SQL_Server_Porc_UnitTest.Properties.Settings.Default.UnitTestConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MySerialNumberDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MySerialNumberDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MySerialNumberDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MySerialNumberDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<my_serial_number> my_serial_number
		{
			get
			{
				return this.GetTable<my_serial_number>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MySerialNumber_CurrVal")]
		public int MySerialNumber_CurrVal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string snName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] ref string snResult)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), snName, snResult);
			snResult = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MySerialNumber_NextVal")]
		public int MySerialNumber_NextVal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string snName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] ref string snResult)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), snName, snResult);
			snResult = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MySerialNumber_FormatVal", IsComposable=true)]
		public string MySerialNumber_FormatVal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sn_format, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> sn_date_curr, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sn_seq_curr)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sn_format, sn_date_curr, sn_seq_curr).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.my_serial_number")]
	public partial class my_serial_number : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sn_id;
		
		private string _sn_name;
		
		private string _sn_desc;
		
		private string _sn_howto;
		
		private string _sn_format;
		
		private int _sn_seq_max;
		
		private int _sn_seq_min;
		
		private int _sn_seq_curr;
		
		private System.Nullable<System.DateTime> _sn_date_curr;
		
		private string _sn_curr_val;
		
		private System.Nullable<bool> _sn_auto_close_date;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsn_idChanging(int value);
    partial void Onsn_idChanged();
    partial void Onsn_nameChanging(string value);
    partial void Onsn_nameChanged();
    partial void Onsn_descChanging(string value);
    partial void Onsn_descChanged();
    partial void Onsn_howtoChanging(string value);
    partial void Onsn_howtoChanged();
    partial void Onsn_formatChanging(string value);
    partial void Onsn_formatChanged();
    partial void Onsn_seq_maxChanging(int value);
    partial void Onsn_seq_maxChanged();
    partial void Onsn_seq_minChanging(int value);
    partial void Onsn_seq_minChanged();
    partial void Onsn_seq_currChanging(int value);
    partial void Onsn_seq_currChanged();
    partial void Onsn_date_currChanging(System.Nullable<System.DateTime> value);
    partial void Onsn_date_currChanged();
    partial void Onsn_curr_valChanging(string value);
    partial void Onsn_curr_valChanged();
    partial void Onsn_auto_close_dateChanging(System.Nullable<bool> value);
    partial void Onsn_auto_close_dateChanged();
    #endregion
		
		public my_serial_number()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sn_id
		{
			get
			{
				return this._sn_id;
			}
			set
			{
				if ((this._sn_id != value))
				{
					this.Onsn_idChanging(value);
					this.SendPropertyChanging();
					this._sn_id = value;
					this.SendPropertyChanged("sn_id");
					this.Onsn_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string sn_name
		{
			get
			{
				return this._sn_name;
			}
			set
			{
				if ((this._sn_name != value))
				{
					this.Onsn_nameChanging(value);
					this.SendPropertyChanging();
					this._sn_name = value;
					this.SendPropertyChanged("sn_name");
					this.Onsn_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn_desc", DbType="NVarChar(50)")]
		public string sn_desc
		{
			get
			{
				return this._sn_desc;
			}
			set
			{
				if ((this._sn_desc != value))
				{
					this.Onsn_descChanging(value);
					this.SendPropertyChanging();
					this._sn_desc = value;
					this.SendPropertyChanged("sn_desc");
					this.Onsn_descChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn_howto", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string sn_howto
		{
			get
			{
				return this._sn_howto;
			}
			set
			{
				if ((this._sn_howto != value))
				{
					this.Onsn_howtoChanging(value);
					this.SendPropertyChanging();
					this._sn_howto = value;
					this.SendPropertyChanged("sn_howto");
					this.Onsn_howtoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn_format", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sn_format
		{
			get
			{
				return this._sn_format;
			}
			set
			{
				if ((this._sn_format != value))
				{
					this.Onsn_formatChanging(value);
					this.SendPropertyChanging();
					this._sn_format = value;
					this.SendPropertyChanged("sn_format");
					this.Onsn_formatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn_seq_max", DbType="Int NOT NULL")]
		public int sn_seq_max
		{
			get
			{
				return this._sn_seq_max;
			}
			set
			{
				if ((this._sn_seq_max != value))
				{
					this.Onsn_seq_maxChanging(value);
					this.SendPropertyChanging();
					this._sn_seq_max = value;
					this.SendPropertyChanged("sn_seq_max");
					this.Onsn_seq_maxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn_seq_min", DbType="Int NOT NULL")]
		public int sn_seq_min
		{
			get
			{
				return this._sn_seq_min;
			}
			set
			{
				if ((this._sn_seq_min != value))
				{
					this.Onsn_seq_minChanging(value);
					this.SendPropertyChanging();
					this._sn_seq_min = value;
					this.SendPropertyChanged("sn_seq_min");
					this.Onsn_seq_minChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn_seq_curr", DbType="Int NOT NULL")]
		public int sn_seq_curr
		{
			get
			{
				return this._sn_seq_curr;
			}
			set
			{
				if ((this._sn_seq_curr != value))
				{
					this.Onsn_seq_currChanging(value);
					this.SendPropertyChanging();
					this._sn_seq_curr = value;
					this.SendPropertyChanged("sn_seq_curr");
					this.Onsn_seq_currChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn_date_curr", DbType="DateTime")]
		public System.Nullable<System.DateTime> sn_date_curr
		{
			get
			{
				return this._sn_date_curr;
			}
			set
			{
				if ((this._sn_date_curr != value))
				{
					this.Onsn_date_currChanging(value);
					this.SendPropertyChanging();
					this._sn_date_curr = value;
					this.SendPropertyChanged("sn_date_curr");
					this.Onsn_date_currChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn_curr_val", DbType="NVarChar(50)")]
		public string sn_curr_val
		{
			get
			{
				return this._sn_curr_val;
			}
			set
			{
				if ((this._sn_curr_val != value))
				{
					this.Onsn_curr_valChanging(value);
					this.SendPropertyChanging();
					this._sn_curr_val = value;
					this.SendPropertyChanged("sn_curr_val");
					this.Onsn_curr_valChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sn_auto_close_date", DbType="Bit")]
		public System.Nullable<bool> sn_auto_close_date
		{
			get
			{
				return this._sn_auto_close_date;
			}
			set
			{
				if ((this._sn_auto_close_date != value))
				{
					this.Onsn_auto_close_dateChanging(value);
					this.SendPropertyChanging();
					this._sn_auto_close_date = value;
					this.SendPropertyChanged("sn_auto_close_date");
					this.Onsn_auto_close_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
