//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace MyWcfServiceLibrary
{
    public partial class TestEntities : ObjectContext
    {
        public const string ConnectionString = "name=TestEntities";
        public const string ContainerName = "TestEntities";
    
        #region Constructors
    
        public TestEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		// 不使用代理类.
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public TestEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		// 不使用代理类.
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public TestEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		// 不使用代理类.
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<test_main> test_main
        {
            get { return _test_main  ?? (_test_main = CreateObjectSet<test_main>("test_main")); }
        }
        private ObjectSet<test_main> _test_main;
    
        public ObjectSet<test_sub> test_sub
        {
            get { return _test_sub  ?? (_test_sub = CreateObjectSet<test_sub>("test_sub")); }
        }
        private ObjectSet<test_sub> _test_sub;

        #endregion
    }
}
