//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("TestModel", "main_id_cons", "test_main", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(A0650_EF_SqlServer.Sample.test_main), "test_sub", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(A0650_EF_SqlServer.Sample.test_sub), true)]
[assembly: EdmRelationshipAttribute("TestModel", "fk_test_score_course", "test_course", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(A0650_EF_SqlServer.Sample.test_course), "test_score", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(A0650_EF_SqlServer.Sample.test_score), true)]
[assembly: EdmRelationshipAttribute("TestModel", "fk_test_score_student", "test_student", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(A0650_EF_SqlServer.Sample.test_student), "test_score", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(A0650_EF_SqlServer.Sample.test_score), true)]
[assembly: EdmRelationshipAttribute("TestModel", "fk_test_sub_s", "test_main", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(A0650_EF_SqlServer.Sample.test_main), "test_sub_s", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(A0650_EF_SqlServer.Sample.test_sub_s), true)]
[assembly: EdmRelationshipAttribute("TestModel", "fk_test_sub_of_sub", "test_sub_s", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(A0650_EF_SqlServer.Sample.test_sub_s), "test_sub_of_sub", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(A0650_EF_SqlServer.Sample.test_sub_of_sub), true)]

#endregion

namespace A0650_EF_SqlServer.Sample
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class TestEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“TestEntities”部分中的连接字符串初始化新 TestEntities 对象。
        /// </summary>
        public TestEntities() : base("name=TestEntities", "TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 TestEntities 对象。
        /// </summary>
        public TestEntities(string connectionString) : base(connectionString, "TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 TestEntities 对象。
        /// </summary>
        public TestEntities(EntityConnection connection) : base(connection, "TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<test_main> test_main
        {
            get
            {
                if ((_test_main == null))
                {
                    _test_main = base.CreateObjectSet<test_main>("test_main");
                }
                return _test_main;
            }
        }
        private ObjectSet<test_main> _test_main;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<test_sub> test_sub
        {
            get
            {
                if ((_test_sub == null))
                {
                    _test_sub = base.CreateObjectSet<test_sub>("test_sub");
                }
                return _test_sub;
            }
        }
        private ObjectSet<test_sub> _test_sub;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<test_sequence> test_sequence
        {
            get
            {
                if ((_test_sequence == null))
                {
                    _test_sequence = base.CreateObjectSet<test_sequence>("test_sequence");
                }
                return _test_sequence;
            }
        }
        private ObjectSet<test_sequence> _test_sequence;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<test_course> test_course
        {
            get
            {
                if ((_test_course == null))
                {
                    _test_course = base.CreateObjectSet<test_course>("test_course");
                }
                return _test_course;
            }
        }
        private ObjectSet<test_course> _test_course;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<test_score> test_score
        {
            get
            {
                if ((_test_score == null))
                {
                    _test_score = base.CreateObjectSet<test_score>("test_score");
                }
                return _test_score;
            }
        }
        private ObjectSet<test_score> _test_score;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<test_student> test_student
        {
            get
            {
                if ((_test_student == null))
                {
                    _test_student = base.CreateObjectSet<test_student>("test_student");
                }
                return _test_student;
            }
        }
        private ObjectSet<test_student> _test_student;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<test_Identity_tab> test_Identity_tab
        {
            get
            {
                if ((_test_Identity_tab == null))
                {
                    _test_Identity_tab = base.CreateObjectSet<test_Identity_tab>("test_Identity_tab");
                }
                return _test_Identity_tab;
            }
        }
        private ObjectSet<test_Identity_tab> _test_Identity_tab;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<test_sub_of_sub> test_sub_of_sub
        {
            get
            {
                if ((_test_sub_of_sub == null))
                {
                    _test_sub_of_sub = base.CreateObjectSet<test_sub_of_sub>("test_sub_of_sub");
                }
                return _test_sub_of_sub;
            }
        }
        private ObjectSet<test_sub_of_sub> _test_sub_of_sub;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<test_sub_s> test_sub_s
        {
            get
            {
                if ((_test_sub_s == null))
                {
                    _test_sub_s = base.CreateObjectSet<test_sub_s>("test_sub_s");
                }
                return _test_sub_s;
            }
        }
        private ObjectSet<test_sub_s> _test_sub_s;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 test_main EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotest_main(test_main test_main)
        {
            base.AddObject("test_main", test_main);
        }
    
        /// <summary>
        /// 用于向 test_sub EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotest_sub(test_sub test_sub)
        {
            base.AddObject("test_sub", test_sub);
        }
    
        /// <summary>
        /// 用于向 test_sequence EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotest_sequence(test_sequence test_sequence)
        {
            base.AddObject("test_sequence", test_sequence);
        }
    
        /// <summary>
        /// 用于向 test_course EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotest_course(test_course test_course)
        {
            base.AddObject("test_course", test_course);
        }
    
        /// <summary>
        /// 用于向 test_score EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotest_score(test_score test_score)
        {
            base.AddObject("test_score", test_score);
        }
    
        /// <summary>
        /// 用于向 test_student EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotest_student(test_student test_student)
        {
            base.AddObject("test_student", test_student);
        }
    
        /// <summary>
        /// 用于向 test_Identity_tab EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotest_Identity_tab(test_Identity_tab test_Identity_tab)
        {
            base.AddObject("test_Identity_tab", test_Identity_tab);
        }
    
        /// <summary>
        /// 用于向 test_sub_of_sub EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotest_sub_of_sub(test_sub_of_sub test_sub_of_sub)
        {
            base.AddObject("test_sub_of_sub", test_sub_of_sub);
        }
    
        /// <summary>
        /// 用于向 test_sub_s EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotest_sub_s(test_sub_s test_sub_s)
        {
            base.AddObject("test_sub_s", test_sub_s);
        }

        #endregion

        #region 函数导入
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        /// <param name="main_val">没有元数据文档可用。</param>
        /// <param name="sub_val">没有元数据文档可用。</param>
        public int TestInsertMainSub(global::System.String main_val, global::System.String sub_val)
        {
            ObjectParameter main_valParameter;
            if (main_val != null)
            {
                main_valParameter = new ObjectParameter("main_val", main_val);
            }
            else
            {
                main_valParameter = new ObjectParameter("main_val", typeof(global::System.String));
            }
    
            ObjectParameter sub_valParameter;
            if (sub_val != null)
            {
                sub_valParameter = new ObjectParameter("sub_val", sub_val);
            }
            else
            {
                sub_valParameter = new ObjectParameter("sub_val", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("TestInsertMainSub", main_valParameter, sub_valParameter);
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        /// <param name="main_id">没有元数据文档可用。</param>
        public int TestRemoveMainSub(Nullable<global::System.Int32> main_id)
        {
            ObjectParameter main_idParameter;
            if (main_id.HasValue)
            {
                main_idParameter = new ObjectParameter("main_id", main_id);
            }
            else
            {
                main_idParameter = new ObjectParameter("main_id", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("TestRemoveMainSub", main_idParameter);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestModel", Name="test_course")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class test_course : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 test_course 对象。
        /// </summary>
        /// <param name="course_code">course_code 属性的初始值。</param>
        /// <param name="course_name">course_name 属性的初始值。</param>
        public static test_course Createtest_course(global::System.Int32 course_code, global::System.String course_name)
        {
            test_course test_course = new test_course();
            test_course.course_code = course_code;
            test_course.course_name = course_name;
            return test_course;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 course_code
        {
            get
            {
                return _course_code;
            }
            set
            {
                if (_course_code != value)
                {
                    Oncourse_codeChanging(value);
                    ReportPropertyChanging("course_code");
                    _course_code = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("course_code");
                    Oncourse_codeChanged();
                }
            }
        }
        private global::System.Int32 _course_code;
        partial void Oncourse_codeChanging(global::System.Int32 value);
        partial void Oncourse_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String course_name
        {
            get
            {
                return _course_name;
            }
            set
            {
                Oncourse_nameChanging(value);
                ReportPropertyChanging("course_name");
                _course_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("course_name");
                Oncourse_nameChanged();
            }
        }
        private global::System.String _course_name;
        partial void Oncourse_nameChanging(global::System.String value);
        partial void Oncourse_nameChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "fk_test_score_course", "test_score")]
        public EntityCollection<test_score> test_score
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<test_score>("TestModel.fk_test_score_course", "test_score");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<test_score>("TestModel.fk_test_score_course", "test_score", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestModel", Name="test_Identity_tab")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class test_Identity_tab : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 test_Identity_tab 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static test_Identity_tab Createtest_Identity_tab(global::System.Int32 id)
        {
            test_Identity_tab test_Identity_tab = new test_Identity_tab();
            test_Identity_tab.id = id;
            return test_Identity_tab;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestModel", Name="test_main")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class test_main : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 test_main 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static test_main Createtest_main(global::System.Int32 id)
        {
            test_main test_main = new test_main();
            test_main.id = id;
            return test_main;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "main_id_cons", "test_sub")]
        public EntityCollection<test_sub> test_sub
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<test_sub>("TestModel.main_id_cons", "test_sub");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<test_sub>("TestModel.main_id_cons", "test_sub", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "fk_test_sub_s", "test_sub_s")]
        public EntityCollection<test_sub_s> test_sub_s
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<test_sub_s>("TestModel.fk_test_sub_s", "test_sub_s");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<test_sub_s>("TestModel.fk_test_sub_s", "test_sub_s", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestModel", Name="test_score")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class test_score : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 test_score 对象。
        /// </summary>
        /// <param name="student_code">student_code 属性的初始值。</param>
        /// <param name="course_code">course_code 属性的初始值。</param>
        /// <param name="score_value">score_value 属性的初始值。</param>
        public static test_score Createtest_score(global::System.Int32 student_code, global::System.Int32 course_code, global::System.Int32 score_value)
        {
            test_score test_score = new test_score();
            test_score.student_code = student_code;
            test_score.course_code = course_code;
            test_score.score_value = score_value;
            return test_score;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 student_code
        {
            get
            {
                return _student_code;
            }
            set
            {
                if (_student_code != value)
                {
                    Onstudent_codeChanging(value);
                    ReportPropertyChanging("student_code");
                    _student_code = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("student_code");
                    Onstudent_codeChanged();
                }
            }
        }
        private global::System.Int32 _student_code;
        partial void Onstudent_codeChanging(global::System.Int32 value);
        partial void Onstudent_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 course_code
        {
            get
            {
                return _course_code;
            }
            set
            {
                if (_course_code != value)
                {
                    Oncourse_codeChanging(value);
                    ReportPropertyChanging("course_code");
                    _course_code = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("course_code");
                    Oncourse_codeChanged();
                }
            }
        }
        private global::System.Int32 _course_code;
        partial void Oncourse_codeChanging(global::System.Int32 value);
        partial void Oncourse_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 score_value
        {
            get
            {
                return _score_value;
            }
            set
            {
                Onscore_valueChanging(value);
                ReportPropertyChanging("score_value");
                _score_value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("score_value");
                Onscore_valueChanged();
            }
        }
        private global::System.Int32 _score_value;
        partial void Onscore_valueChanging(global::System.Int32 value);
        partial void Onscore_valueChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "fk_test_score_course", "test_course")]
        public test_course test_course
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_course>("TestModel.fk_test_score_course", "test_course").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_course>("TestModel.fk_test_score_course", "test_course").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<test_course> test_courseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_course>("TestModel.fk_test_score_course", "test_course");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<test_course>("TestModel.fk_test_score_course", "test_course", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "fk_test_score_student", "test_student")]
        public test_student test_student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_student>("TestModel.fk_test_score_student", "test_student").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_student>("TestModel.fk_test_score_student", "test_student").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<test_student> test_studentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_student>("TestModel.fk_test_score_student", "test_student");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<test_student>("TestModel.fk_test_score_student", "test_student", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestModel", Name="test_sequence")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class test_sequence : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 test_sequence 对象。
        /// </summary>
        /// <param name="table_name">table_name 属性的初始值。</param>
        /// <param name="sequence_number">sequence_number 属性的初始值。</param>
        public static test_sequence Createtest_sequence(global::System.String table_name, global::System.Int32 sequence_number)
        {
            test_sequence test_sequence = new test_sequence();
            test_sequence.table_name = table_name;
            test_sequence.sequence_number = sequence_number;
            return test_sequence;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String table_name
        {
            get
            {
                return _table_name;
            }
            set
            {
                if (_table_name != value)
                {
                    Ontable_nameChanging(value);
                    ReportPropertyChanging("table_name");
                    _table_name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("table_name");
                    Ontable_nameChanged();
                }
            }
        }
        private global::System.String _table_name;
        partial void Ontable_nameChanging(global::System.String value);
        partial void Ontable_nameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sequence_number
        {
            get
            {
                return _sequence_number;
            }
            set
            {
                Onsequence_numberChanging(value);
                ReportPropertyChanging("sequence_number");
                _sequence_number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sequence_number");
                Onsequence_numberChanged();
            }
        }
        private global::System.Int32 _sequence_number;
        partial void Onsequence_numberChanging(global::System.Int32 value);
        partial void Onsequence_numberChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestModel", Name="test_student")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class test_student : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 test_student 对象。
        /// </summary>
        /// <param name="student_code">student_code 属性的初始值。</param>
        /// <param name="student_name">student_name 属性的初始值。</param>
        public static test_student Createtest_student(global::System.Int32 student_code, global::System.String student_name)
        {
            test_student test_student = new test_student();
            test_student.student_code = student_code;
            test_student.student_name = student_name;
            return test_student;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 student_code
        {
            get
            {
                return _student_code;
            }
            set
            {
                if (_student_code != value)
                {
                    Onstudent_codeChanging(value);
                    ReportPropertyChanging("student_code");
                    _student_code = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("student_code");
                    Onstudent_codeChanged();
                }
            }
        }
        private global::System.Int32 _student_code;
        partial void Onstudent_codeChanging(global::System.Int32 value);
        partial void Onstudent_codeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String student_name
        {
            get
            {
                return _student_name;
            }
            set
            {
                Onstudent_nameChanging(value);
                ReportPropertyChanging("student_name");
                _student_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("student_name");
                Onstudent_nameChanged();
            }
        }
        private global::System.String _student_name;
        partial void Onstudent_nameChanging(global::System.String value);
        partial void Onstudent_nameChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "fk_test_score_student", "test_score")]
        public EntityCollection<test_score> test_score
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<test_score>("TestModel.fk_test_score_student", "test_score");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<test_score>("TestModel.fk_test_score_student", "test_score", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestModel", Name="test_sub")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class test_sub : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 test_sub 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static test_sub Createtest_sub(global::System.Int32 id)
        {
            test_sub test_sub = new test_sub();
            test_sub.id = id;
            return test_sub;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> main_id
        {
            get
            {
                return _main_id;
            }
            set
            {
                Onmain_idChanging(value);
                ReportPropertyChanging("main_id");
                _main_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("main_id");
                Onmain_idChanged();
            }
        }
        private Nullable<global::System.Int32> _main_id;
        partial void Onmain_idChanging(Nullable<global::System.Int32> value);
        partial void Onmain_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "main_id_cons", "test_main")]
        public test_main test_main
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_main>("TestModel.main_id_cons", "test_main").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_main>("TestModel.main_id_cons", "test_main").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<test_main> test_mainReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_main>("TestModel.main_id_cons", "test_main");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<test_main>("TestModel.main_id_cons", "test_main", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestModel", Name="test_sub_of_sub")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class test_sub_of_sub : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 test_sub_of_sub 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static test_sub_of_sub Createtest_sub_of_sub(global::System.Int32 id)
        {
            test_sub_of_sub test_sub_of_sub = new test_sub_of_sub();
            test_sub_of_sub.id = id;
            return test_sub_of_sub;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> sub_main_id
        {
            get
            {
                return _sub_main_id;
            }
            set
            {
                Onsub_main_idChanging(value);
                ReportPropertyChanging("sub_main_id");
                _sub_main_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sub_main_id");
                Onsub_main_idChanged();
            }
        }
        private Nullable<global::System.Int32> _sub_main_id;
        partial void Onsub_main_idChanging(Nullable<global::System.Int32> value);
        partial void Onsub_main_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "fk_test_sub_of_sub", "test_sub_s")]
        public test_sub_s test_sub_s
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_sub_s>("TestModel.fk_test_sub_of_sub", "test_sub_s").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_sub_s>("TestModel.fk_test_sub_of_sub", "test_sub_s").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<test_sub_s> test_sub_sReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_sub_s>("TestModel.fk_test_sub_of_sub", "test_sub_s");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<test_sub_s>("TestModel.fk_test_sub_of_sub", "test_sub_s", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestModel", Name="test_sub_s")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class test_sub_s : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 test_sub_s 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static test_sub_s Createtest_sub_s(global::System.Int32 id)
        {
            test_sub_s test_sub_s = new test_sub_s();
            test_sub_s.id = id;
            return test_sub_s;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> main_id
        {
            get
            {
                return _main_id;
            }
            set
            {
                Onmain_idChanging(value);
                ReportPropertyChanging("main_id");
                _main_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("main_id");
                Onmain_idChanged();
            }
        }
        private Nullable<global::System.Int32> _main_id;
        partial void Onmain_idChanging(Nullable<global::System.Int32> value);
        partial void Onmain_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "fk_test_sub_s", "test_main")]
        public test_main test_main
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_main>("TestModel.fk_test_sub_s", "test_main").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_main>("TestModel.fk_test_sub_s", "test_main").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<test_main> test_mainReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<test_main>("TestModel.fk_test_sub_s", "test_main");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<test_main>("TestModel.fk_test_sub_s", "test_main", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TestModel", "fk_test_sub_of_sub", "test_sub_of_sub")]
        public EntityCollection<test_sub_of_sub> test_sub_of_sub
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<test_sub_of_sub>("TestModel.fk_test_sub_of_sub", "test_sub_of_sub");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<test_sub_of_sub>("TestModel.fk_test_sub_of_sub", "test_sub_of_sub", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
