' CREATED		2013/9/13
' MODIFIED		2013/9/13
' PROJECT		
' MODEL			
' COMPANY		
' AUTHOR			
' VERSION		
' DATABASE		ACCESS 2000 

'=======================================================
'=== MS ACCESS 2000 DATABASE CREATION METHOD
'===
'=== 1. CREATE A NEW DATABASE IN THE MS ACCESS 2000
'=== 2. CREATE A NEW MODULE
'=== 3. COPY THE TOAD DATA MODELER OUTPUT SQL SCRIPT INTO THE NEW MS ACCESS 2000 MODULE
'=== 4. SELECT FROM MAIN MENU "TOOLS" ITEM "REFERENCES..." AND CHECK THE "MICROSOFT DAO 3.6 OBJECT LIBRARY."
'=== 5. PLACE YOUR MOUSE CURSOR SOMEWHERE IN THE MAIN PROCEDURE MAIN()
'=== 6. RUN THE MODULE CODE (CLICK THE "RUN SUB/USERFORM" BUTTON OR PRESS F5)
'=======================================================

PUBLIC DBS AS DAO.DATABASE
PUBLIC TDF AS DAO.TABLEDEF
PUBLIC IDX AS DAO.INDEX
PUBLIC REL AS DAO.RELATION

SUB MAIN()

SET DBS = CURRENTDB()

ON ERROR GOTO ERRORHANDLER
	
	
	
	
	CALL CREATETABLES
	
	CALL CREATEPRIMARYKEYS
	CALL CREATEINDEXES
	
	CALL CREATERELATIONS
	
	
	
	MSGBOX "SCRIPT SUCCESSFULLY PROCESSED.", VBINFORMATION
	EXIT SUB
	
ERRORHANDLER:
	SELECT CASE ERR.NUMBER
		CASE 3010
			MSGBOX "TABLE " & TDF.NAME & " ALREADY EXIST!", VBINFORMATION
			ERR.CLEAR
      CASE 3284
         MSGBOX "INDEX " & IDX.NAME & " FOR TABLE " & TDF.NAME & " ALREADY EXIST!", VBINFORMATION
         ERR.CLEAR
		CASE ELSE
			MSGBOX ERR.DESCRIPTION, VBCRITICAL
	END SELECT
END SUB


' CREATE TABLES
'===============

SUB CREATETABLES()

CALL CREATETABLE1 'HR_BRANCH
CALL CREATETABLE2 'HR_STAFF
CALL CREATETABLE3 'HR_STAFF_TITLE
CALL CREATETABLE4 'HR_ROSTERS
CALL CREATETABLE5 'HR_PUBLICHOLIDAY
CALL CREATETABLE6 'HR_PUBLICHOLIDAYSTAFF
CALL CREATETABLE7 'HR_STAFFSHIFTSHOP
CALL CREATETABLE8 'HR_BRANCHSHIFT
END SUB

'=== CREATE TABLE HR_BRANCH ======

SUB CREATETABLE1()

SET TDF = DBS.CREATETABLEDEF( "HR_BRANCH" )

CALL ADDFIELDTOTABLE("BRANCH_CODE", DBTEXT, 20, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("BRANCH_NAME_CHI", DBTEXT, 50, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("BRANCH_NAME_ENG", DBTEXT, 100, 0, "", "", "", FALSE, FALSE )
CALL ADDFIELDTOTABLE("BRANCH_CREATEDATE", DBDATE, 0, 0, "", "", "", FALSE, FALSE )
CALL ADDFIELDTOTABLE("BRANCH_STATUS", DBTEXT, 10, 0, "", "", "", FALSE, FALSE )

DBS.TABLEDEFS.APPEND TDF

CALL ADDPROPERTYTOTABLE( "DESCRIPTION","店铺表",DBTEXT)
CALL ADDPROPERTYTOFIELD( "BRANCH_CODE","DESCRIPTION","商店代码",DBTEXT)
CALL ADDPROPERTYTOFIELD( "BRANCH_NAME_CHI","DESCRIPTION","店铺名称(中文)",DBTEXT)
CALL ADDPROPERTYTOFIELD( "BRANCH_NAME_ENG","DESCRIPTION","店铺名称(英文)",DBTEXT)
CALL ADDPROPERTYTOFIELD( "BRANCH_CREATEDATE","DESCRIPTION","店铺创建日期",DBTEXT)
CALL ADDPROPERTYTOFIELD( "BRANCH_STATUS","DESCRIPTION","店铺状态",DBTEXT)


END SUB

'=== CREATE TABLE HR_STAFF ======

SUB CREATETABLE2()

SET TDF = DBS.CREATETABLEDEF( "HR_STAFF" )

CALL ADDFIELDTOTABLE("STAFF_CODE", DBTEXT, 20, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("BRANCH_CODE", DBTEXT, 20, 0, "", "", "", FALSE, FALSE )
CALL ADDFIELDTOTABLE("TITLE_CODE", DBTEXT, 20, 0, "", "", "", FALSE, FALSE )
CALL ADDFIELDTOTABLE("STAFF_NAME_CHI", DBTEXT, 20, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("STAFF_NAME_ENG", DBTEXT, 100, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("STAFF_EMAILADDRESS", DBTEXT, 50, 0, "", "", "", FALSE, FALSE )
CALL ADDFIELDTOTABLE("STAFF_DATECREATE", DBDATE, 0, 0, "", "", "", FALSE, FALSE )
CALL ADDFIELDTOTABLE("STAFF_DATELEAVE", DBDATE, 0, 0, "", "", "", FALSE, FALSE )

DBS.TABLEDEFS.APPEND TDF

CALL ADDPROPERTYTOTABLE( "DESCRIPTION","员工表",DBTEXT)
CALL ADDPROPERTYTOFIELD( "STAFF_CODE","DESCRIPTION","员工代码",DBTEXT)
CALL ADDPROPERTYTOFIELD( "BRANCH_CODE","DESCRIPTION","所属商店代码",DBTEXT)
CALL ADDPROPERTYTOFIELD( "TITLE_CODE","DESCRIPTION","职位",DBTEXT)
CALL ADDPROPERTYTOFIELD( "STAFF_NAME_CHI","DESCRIPTION","员工姓名(中文)",DBTEXT)
CALL ADDPROPERTYTOFIELD( "STAFF_NAME_ENG","DESCRIPTION","员工姓名(英文)",DBTEXT)
CALL ADDPROPERTYTOFIELD( "STAFF_EMAILADDRESS","DESCRIPTION","员工电子邮件",DBTEXT)
CALL ADDPROPERTYTOFIELD( "STAFF_DATECREATE","DESCRIPTION","入职日期",DBTEXT)
CALL ADDPROPERTYTOFIELD( "STAFF_DATELEAVE","DESCRIPTION","离职日期",DBTEXT)


END SUB

'=== CREATE TABLE HR_STAFF_TITLE ======

SUB CREATETABLE3()

SET TDF = DBS.CREATETABLEDEF( "HR_STAFF_TITLE" )

CALL ADDFIELDTOTABLE("TITLE_CODE", DBTEXT, 20, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("TITLE_NAME_CHI", DBTEXT, 50, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("TITLE_NAME_ENG", DBTEXT, 100, 0, "", "", "", FALSE, FALSE )
CALL ADDFIELDTOTABLE("TITLE_PRIORITY", DBLONG, 0, 0, "0", "", "", FALSE, FALSE )
CALL ADDFIELDTOTABLE("TITLE_EXP_DATA", DBTEXT, 200, 0, "", "", "", FALSE, FALSE )

DBS.TABLEDEFS.APPEND TDF

CALL ADDPROPERTYTOFIELD( "TITLE_CODE","DESCRIPTION","职位编号",DBTEXT)
CALL ADDPROPERTYTOFIELD( "TITLE_NAME_CHI","DESCRIPTION","职位名(中文)",DBTEXT)
CALL ADDPROPERTYTOFIELD( "TITLE_NAME_ENG","DESCRIPTION","职位名(英文)",DBTEXT)
CALL ADDPROPERTYTOFIELD( "TITLE_PRIORITY","DESCRIPTION","职位优先级标志",DBTEXT)
CALL ADDPROPERTYTOFIELD( "TITLE_EXP_DATA","DESCRIPTION","职位扩展数据",DBTEXT)


END SUB

'=== CREATE TABLE HR_ROSTERS ======

SUB CREATETABLE4()

SET TDF = DBS.CREATETABLEDEF( "HR_ROSTERS" )

CALL ADDFIELDTOTABLE("ROSTER_ID", DBLONG, 0, DBAUTOINCRFIELD, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("BRANCH_CODE", DBTEXT, 20, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("STAFF_CODE", DBTEXT, 20, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("ROSTER_DATE", DBDATE, 0, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("BRANCHSHIFT_CODE", DBTEXT, 10, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("ROSTER_QUEUEPOS", DBLONG, 0, 0, "0", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("ROSTER_SHIFTLOCK", DBINTEGER, 0, 0, "0", "", "", TRUE, FALSE )

DBS.TABLEDEFS.APPEND TDF

CALL ADDPROPERTYTOTABLE( "DESCRIPTION","排班表",DBTEXT)
CALL ADDPROPERTYTOFIELD( "ROSTER_ID","DESCRIPTION","排班ID",DBTEXT)
CALL ADDPROPERTYTOFIELD( "BRANCH_CODE","DESCRIPTION","商店代码",DBTEXT)
CALL ADDPROPERTYTOFIELD( "STAFF_CODE","DESCRIPTION","员工代码",DBTEXT)
CALL ADDPROPERTYTOFIELD( "ROSTER_DATE","DESCRIPTION","排班日期",DBTEXT)
CALL ADDPROPERTYTOFIELD( "ROSTER_QUEUEPOS","DESCRIPTION","显示顺序（预约用）",DBTEXT)
CALL ADDPROPERTYTOFIELD( "ROSTER_SHIFTLOCK","DESCRIPTION","是否是锁定",DBTEXT)


END SUB

'=== CREATE TABLE HR_PUBLICHOLIDAY ======

SUB CREATETABLE5()

SET TDF = DBS.CREATETABLEDEF( "HR_PUBLICHOLIDAY" )

CALL ADDFIELDTOTABLE("PUBLICHOLIDAY_CODE", DBTEXT, 20, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("PUBLICHOLIDAY_DATE", DBDATE, 0, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("PUBLICHOLIDAY_NAME_CHI", DBTEXT, 50, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("PUBLICHOLIDAY_NAME_ENG", DBTEXT, 100, 0, "", "", "", FALSE, FALSE )

DBS.TABLEDEFS.APPEND TDF

CALL ADDPROPERTYTOTABLE( "DESCRIPTION","公共假日表",DBTEXT)
CALL ADDPROPERTYTOFIELD( "PUBLICHOLIDAY_CODE","DESCRIPTION","公共假日代码",DBTEXT)
CALL ADDPROPERTYTOFIELD( "PUBLICHOLIDAY_DATE","DESCRIPTION","公共假日日期",DBTEXT)
CALL ADDPROPERTYTOFIELD( "PUBLICHOLIDAY_NAME_CHI","DESCRIPTION","公共假日名称(中文)",DBTEXT)
CALL ADDPROPERTYTOFIELD( "PUBLICHOLIDAY_NAME_ENG","DESCRIPTION","公共假日名称(英文)",DBTEXT)


END SUB

'=== CREATE TABLE HR_PUBLICHOLIDAYSTAFF ======

SUB CREATETABLE6()

SET TDF = DBS.CREATETABLEDEF( "HR_PUBLICHOLIDAYSTAFF" )

CALL ADDFIELDTOTABLE("STAFF_CODE", DBTEXT, 20, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("PUBLICHOLIDAY_CODE", DBTEXT, 20, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("PUBLICHOLIDAY_DATE", DBDATE, 0, 0, "", "", "", FALSE, FALSE )
CALL ADDFIELDTOTABLE("STAFF_USE_DATE", DBDATE, 0, 0, "", "", "", FALSE, FALSE )
CALL ADDFIELDTOTABLE("REQUEST_FLAG", DBINTEGER, 0, 0, "0", "", "", FALSE, FALSE )

DBS.TABLEDEFS.APPEND TDF

CALL ADDPROPERTYTOTABLE( "DESCRIPTION","员工-公共假日休假关联表",DBTEXT)
CALL ADDPROPERTYTOFIELD( "STAFF_CODE","DESCRIPTION","员工代码",DBTEXT)
CALL ADDPROPERTYTOFIELD( "PUBLICHOLIDAY_DATE","DESCRIPTION","公共休假日期",DBTEXT)
CALL ADDPROPERTYTOFIELD( "STAFF_USE_DATE","DESCRIPTION","员工实际休息日期",DBTEXT)
CALL ADDPROPERTYTOFIELD( "REQUEST_FLAG","DESCRIPTION","是否锁定",DBTEXT)


END SUB

'=== CREATE TABLE HR_STAFFSHIFTSHOP ======

SUB CREATETABLE7()

SET TDF = DBS.CREATETABLEDEF( "HR_STAFFSHIFTSHOP" )

CALL ADDFIELDTOTABLE("STAFFSHIFTSHOP_ID", DBLONG, 0, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("STAFF_CODE", DBTEXT, 20, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("BRANCH_CODE", DBTEXT, 20, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("START_SHIFT", DBDATE, 0, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("END_SHIFT", DBDATE, 0, 0, "", "", "", TRUE, FALSE )

DBS.TABLEDEFS.APPEND TDF

CALL ADDPROPERTYTOTABLE( "DESCRIPTION","员工借铺表(TR)",DBTEXT)
CALL ADDPROPERTYTOFIELD( "STAFFSHIFTSHOP_ID","DESCRIPTION","借铺ID",DBTEXT)
CALL ADDPROPERTYTOFIELD( "START_SHIFT","DESCRIPTION","借铺起始日期",DBTEXT)
CALL ADDPROPERTYTOFIELD( "END_SHIFT","DESCRIPTION","借铺结束日期",DBTEXT)


END SUB

'=== CREATE TABLE HR_BRANCHSHIFT ======

SUB CREATETABLE8()

SET TDF = DBS.CREATETABLEDEF( "HR_BRANCHSHIFT" )

CALL ADDFIELDTOTABLE("BRANCHSHIFT_CODE", DBTEXT, 10, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("BRANCH_CODE", DBTEXT, 20, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("BRANCHSHIFT_SHIFTNAME", DBTEXT, 20, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("BRANCHSHIFT_STARTTIME", DBTEXT, 4, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("BRANCHSHIFT_ENDTIME", DBTEXT, 4, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("BRANCHSHIFT_STARTDATE", DBDATE, 0, 0, "", "", "", TRUE, FALSE )
CALL ADDFIELDTOTABLE("BRANCHSHIFT_ENDDATE", DBDATE, 0, 0, "", "", "", FALSE, FALSE )

DBS.TABLEDEFS.APPEND TDF

CALL ADDPROPERTYTOTABLE( "DESCRIPTION","商店排班 班次表",DBTEXT)
CALL ADDPROPERTYTOFIELD( "BRANCHSHIFT_CODE","DESCRIPTION","排班班次ID",DBTEXT)
CALL ADDPROPERTYTOFIELD( "BRANCHSHIFT_SHIFTNAME","DESCRIPTION","排班名称",DBTEXT)
CALL ADDPROPERTYTOFIELD( "BRANCHSHIFT_STARTTIME","DESCRIPTION","上班时间",DBTEXT)
CALL ADDPROPERTYTOFIELD( "BRANCHSHIFT_ENDTIME","DESCRIPTION","下班时间",DBTEXT)
CALL ADDPROPERTYTOFIELD( "BRANCHSHIFT_STARTDATE","DESCRIPTION","开始生效日期",DBTEXT)
CALL ADDPROPERTYTOFIELD( "BRANCHSHIFT_ENDDATE","DESCRIPTION","结束生效日期",DBTEXT)


END SUB



' CREATE PRIMARY KEYS
'=====================

SUB CREATEPRIMARYKEYS()

'=== CREATE PRIMARY KEY FOR TABLE HR_BRANCH ======

SET TDF = DBS.TABLEDEFS( "HR_BRANCH" )
SET IDX = TDF.CREATEINDEX( "PK_HR_BRANCH" )

IDX.PRIMARY = TRUE
IDX.UNIQUE  = TRUE
IDX.IGNORENULLS = FALSE

CALL ADDFIELDTOINDEX( "BRANCH_CODE", FALSE )

TDF.INDEXES.APPEND IDX

'=== CREATE PRIMARY KEY FOR TABLE HR_STAFF ======

SET TDF = DBS.TABLEDEFS( "HR_STAFF" )
SET IDX = TDF.CREATEINDEX( "PK_HR_STAFF" )

IDX.PRIMARY = TRUE
IDX.UNIQUE  = TRUE
IDX.IGNORENULLS = FALSE

CALL ADDFIELDTOINDEX( "STAFF_CODE", FALSE )

TDF.INDEXES.APPEND IDX

'=== CREATE PRIMARY KEY FOR TABLE HR_STAFF_TITLE ======

SET TDF = DBS.TABLEDEFS( "HR_STAFF_TITLE" )
SET IDX = TDF.CREATEINDEX( "PK_HR_STAFF_TITLE" )

IDX.PRIMARY = TRUE
IDX.UNIQUE  = TRUE
IDX.IGNORENULLS = FALSE

CALL ADDFIELDTOINDEX( "TITLE_CODE", FALSE )

TDF.INDEXES.APPEND IDX

'=== CREATE PRIMARY KEY FOR TABLE HR_ROSTERS ======

SET TDF = DBS.TABLEDEFS( "HR_ROSTERS" )
SET IDX = TDF.CREATEINDEX( "PK_HR_ROSTERS" )

IDX.PRIMARY = TRUE
IDX.UNIQUE  = TRUE
IDX.IGNORENULLS = FALSE

CALL ADDFIELDTOINDEX( "ROSTER_ID", FALSE )

TDF.INDEXES.APPEND IDX

'=== CREATE PRIMARY KEY FOR TABLE HR_PUBLICHOLIDAY ======

SET TDF = DBS.TABLEDEFS( "HR_PUBLICHOLIDAY" )
SET IDX = TDF.CREATEINDEX( "PK_HR_PUBLICHOLIDAY" )

IDX.PRIMARY = TRUE
IDX.UNIQUE  = TRUE
IDX.IGNORENULLS = FALSE

CALL ADDFIELDTOINDEX( "PUBLICHOLIDAY_CODE", FALSE )

TDF.INDEXES.APPEND IDX

'=== CREATE PRIMARY KEY FOR TABLE HR_PUBLICHOLIDAYSTAFF ======

SET TDF = DBS.TABLEDEFS( "HR_PUBLICHOLIDAYSTAFF" )
SET IDX = TDF.CREATEINDEX( "PK_HR_PUBLICHOLIDAYSTAFF" )

IDX.PRIMARY = TRUE
IDX.UNIQUE  = TRUE
IDX.IGNORENULLS = FALSE

CALL ADDFIELDTOINDEX( "STAFF_CODE", FALSE )
CALL ADDFIELDTOINDEX( "PUBLICHOLIDAY_CODE", FALSE )

TDF.INDEXES.APPEND IDX

'=== CREATE PRIMARY KEY FOR TABLE HR_STAFFSHIFTSHOP ======

SET TDF = DBS.TABLEDEFS( "HR_STAFFSHIFTSHOP" )
SET IDX = TDF.CREATEINDEX( "PK_HR_STAFFSHIFTSHOP" )

IDX.PRIMARY = TRUE
IDX.UNIQUE  = TRUE
IDX.IGNORENULLS = FALSE

CALL ADDFIELDTOINDEX( "STAFFSHIFTSHOP_ID", FALSE )

TDF.INDEXES.APPEND IDX

'=== CREATE PRIMARY KEY FOR TABLE HR_BRANCHSHIFT ======

SET TDF = DBS.TABLEDEFS( "HR_BRANCHSHIFT" )
SET IDX = TDF.CREATEINDEX( "PK_HR_BRANCHSHIFT" )

IDX.PRIMARY = TRUE
IDX.UNIQUE  = TRUE
IDX.IGNORENULLS = FALSE

CALL ADDFIELDTOINDEX( "BRANCHSHIFT_CODE", FALSE )

TDF.INDEXES.APPEND IDX


END SUB


' CREATE INDEXES
'================

SUB CREATEINDEXES()


END SUB

' CREATE RELATIONS
'==================

SUB CREATERELATIONS()
'=== CREATE RELATIONS BETWEEN PARENT TABLE HR_BRANCH AND CHILD TABLE HR_STAFF ======

SET REL = DBS.CREATERELATION("FK_REF_STAFF_BRANCH")

REL.TABLE			= "HR_BRANCH"
REL.FOREIGNTABLE	= "HR_STAFF"
REL.ATTRIBUTES	= 0

CALL ADDFIELDTORELATION("BRANCH_CODE", "BRANCH_CODE")

DBS.RELATIONS.APPEND REL


'=== CREATE RELATIONS BETWEEN PARENT TABLE HR_BRANCH AND CHILD TABLE HR_ROSTERS ======

SET REL = DBS.CREATERELATION("FK_ROSTER_BRANCH")

REL.TABLE			= "HR_BRANCH"
REL.FOREIGNTABLE	= "HR_ROSTERS"
REL.ATTRIBUTES	= 0

CALL ADDFIELDTORELATION("BRANCH_CODE", "BRANCH_CODE")

DBS.RELATIONS.APPEND REL


'=== CREATE RELATIONS BETWEEN PARENT TABLE HR_BRANCH AND CHILD TABLE HR_STAFFSHIFTSHOP ======

SET REL = DBS.CREATERELATION("FK_STAFFSHIFTSHOP_SHOP")

REL.TABLE			= "HR_BRANCH"
REL.FOREIGNTABLE	= "HR_STAFFSHIFTSHOP"
REL.ATTRIBUTES	= 0

CALL ADDFIELDTORELATION("BRANCH_CODE", "BRANCH_CODE")

DBS.RELATIONS.APPEND REL


'=== CREATE RELATIONS BETWEEN PARENT TABLE HR_BRANCH AND CHILD TABLE HR_BRANCHSHIFT ======

SET REL = DBS.CREATERELATION("FK_BRANCHSHIFT_BRANCH")

REL.TABLE			= "HR_BRANCH"
REL.FOREIGNTABLE	= "HR_BRANCHSHIFT"
REL.ATTRIBUTES	= 0

CALL ADDFIELDTORELATION("BRANCH_CODE", "BRANCH_CODE")

DBS.RELATIONS.APPEND REL


'=== CREATE RELATIONS BETWEEN PARENT TABLE HR_STAFF AND CHILD TABLE HR_PUBLICHOLIDAYSTAFF ======

SET REL = DBS.CREATERELATION("FK_PUBLICHOLIDAYSTAFF_S")

REL.TABLE			= "HR_STAFF"
REL.FOREIGNTABLE	= "HR_PUBLICHOLIDAYSTAFF"
REL.ATTRIBUTES	= 0

CALL ADDFIELDTORELATION("STAFF_CODE", "STAFF_CODE")

DBS.RELATIONS.APPEND REL


'=== CREATE RELATIONS BETWEEN PARENT TABLE HR_STAFF AND CHILD TABLE HR_ROSTERS ======

SET REL = DBS.CREATERELATION("FK_ROSTER_STAFF")

REL.TABLE			= "HR_STAFF"
REL.FOREIGNTABLE	= "HR_ROSTERS"
REL.ATTRIBUTES	= 0

CALL ADDFIELDTORELATION("STAFF_CODE", "STAFF_CODE")

DBS.RELATIONS.APPEND REL


'=== CREATE RELATIONS BETWEEN PARENT TABLE HR_STAFF AND CHILD TABLE HR_STAFFSHIFTSHOP ======

SET REL = DBS.CREATERELATION("FK_STAFFSHIFTSHOP_STAFF")

REL.TABLE			= "HR_STAFF"
REL.FOREIGNTABLE	= "HR_STAFFSHIFTSHOP"
REL.ATTRIBUTES	= 0

CALL ADDFIELDTORELATION("STAFF_CODE", "STAFF_CODE")

DBS.RELATIONS.APPEND REL


'=== CREATE RELATIONS BETWEEN PARENT TABLE HR_STAFF_TITLE AND CHILD TABLE HR_STAFF ======

SET REL = DBS.CREATERELATION("FK_REF_STAFF_TITLE")

REL.TABLE			= "HR_STAFF_TITLE"
REL.FOREIGNTABLE	= "HR_STAFF"
REL.ATTRIBUTES	= 0

CALL ADDFIELDTORELATION("TITLE_CODE", "TITLE_CODE")

DBS.RELATIONS.APPEND REL


'=== CREATE RELATIONS BETWEEN PARENT TABLE HR_PUBLICHOLIDAY AND CHILD TABLE HR_PUBLICHOLIDAYSTAFF ======

SET REL = DBS.CREATERELATION("FK_PUBLICHOLIDAYSTAFF_P")

REL.TABLE			= "HR_PUBLICHOLIDAY"
REL.FOREIGNTABLE	= "HR_PUBLICHOLIDAYSTAFF"
REL.ATTRIBUTES	= 0

CALL ADDFIELDTORELATION("PUBLICHOLIDAY_CODE", "PUBLICHOLIDAY_CODE")

DBS.RELATIONS.APPEND REL


'=== CREATE RELATIONS BETWEEN PARENT TABLE HR_BRANCHSHIFT AND CHILD TABLE HR_ROSTERS ======

SET REL = DBS.CREATERELATION("FK_ROSTER_BRANCHSHIFT")

REL.TABLE			= "HR_BRANCHSHIFT"
REL.FOREIGNTABLE	= "HR_ROSTERS"
REL.ATTRIBUTES	= 0

CALL ADDFIELDTORELATION("BRANCHSHIFT_CODE", "BRANCHSHIFT_CODE")

DBS.RELATIONS.APPEND REL



END SUB


' ADD FIELDS TO TABLE
'=====================

SUB ADDFIELDTOTABLE(FIELDNAME AS STRING, DATATYPE AS STRING, SIZECOL AS INTEGER, ATTRIBUTES AS LONG, DEFAULTVALUE AS VARIANT, VALTEXT AS STRING, VALRULE AS STRING, NOTN AS BOOLEAN, ZEROLENGTH AS BOOLEAN)

DIM FLD AS DAO.FIELD

SET FLD = TDF.CREATEFIELD( FIELDNAME, DATATYPE )

IF SIZECOL 		<> 0 THEN FLD.SIZE	   	= SIZECOL
IF ATTRIBUTES	<> 0 THEN FLD.ATTRIBUTES	= ATTRIBUTES

FLD.REQUIRED 			= NOTN
IF DATATYPE = DBTEXT OR DATATYPE = DBMEMO THEN FLD.ALLOWZEROLENGTH = ZEROLENGTH
FLD.DEFAULTVALUE 		= DEFAULTVALUE
FLD.VALIDATIONRULE 	= VALRULE
FLD.VALIDATIONTEXT 	= VALTEXT

TDF.FIELDS.APPEND FLD

END SUB

' ADD PROPERTIES TO TABLE
'=========================

SUB ADDPROPERTYTOTABLE( PROPERTYNAME AS STRING, VALUE AS VARIANT, DATATYPE AS STRING)

DIM PRP AS DAO.PROPERTY

SET PRP = TDF.CREATEPROPERTY(PROPERTYNAME, DATATYPE, VALUE)

TDF.PROPERTIES.APPEND PRP

END SUB


' ADD PROPERTIES TO FIELD
'=========================

SUB ADDPROPERTYTOFIELD( FIELDNAME AS STRING, PROPERTYNAME AS STRING, VALUE AS VARIANT, DATATYPE AS STRING)

DIM PRP AS DAO.PROPERTY
DIM FLD AS DAO.FIELD

SET FLD = TDF.FIELDS( FIELDNAME )
SET PRP = FLD.CREATEPROPERTY(PROPERTYNAME, DATATYPE, VALUE)

FLD.PROPERTIES.APPEND PRP

END SUB


' ADD FIELDS TO INDEX
'=====================

SUB ADDFIELDTOINDEX( FIELDNAME AS STRING, DESCENDING AS BOOLEAN )

DIM FLD AS DAO.FIELD

SET FLD = IDX.CREATEFIELD( FIELDNAME )

IF DESCENDING = TRUE THEN FLD.ATTRIBUTES = DBDESCENDING

IDX.FIELDS.APPEND FLD

END SUB


' ADD FIELDS TO RELATION
'========================

SUB ADDFIELDTORELATION( PKFIELD AS STRING, FKFIELD AS STRING )

DIM FLD AS DAO.FIELD

SET FLD = REL.CREATEFIELD( PKFIELD )

FLD.FOREIGNNAME = FKFIELD

REL.FIELDS.APPEND FLD

END SUB


