//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("A0610_EF.Sample", "FK__goods__type_id__1273C1CD", "goods_type", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(A0610_EF.Sample.goods_type), "goods", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(A0610_EF.Sample.goods))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("A0610_EF.Sample", "FK__onhand__goodsid__117F9D94", "goods", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(A0610_EF.Sample.goods), "onhand", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(A0610_EF.Sample.onhand))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("A0610_EF.Sample", "FK__onhand__store_id__1367E606", "store", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(A0610_EF.Sample.store), "onhand", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(A0610_EF.Sample.onhand))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("A0610_EF.Sample", "main_id_cons", "test_main", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(A0610_EF.Sample.test_main), "test_sub", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(A0610_EF.Sample.test_sub))]

// 原始文件名: Test.ObjectLayer.cs
// 生成日期: 2010-12-17 22:46:41
namespace A0610_EF.Sample
{
    
    /// <summary>
    /// 架构中不存在 TestContext 的注释。
    /// </summary>
    public partial class TestContext : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// 请使用应用程序配置文件的“TestContext”部分中的连接字符串初始化新 TestContext 对象。
        /// </summary>
        public TestContext() : 
                base("name=TestContext", "TestContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 TestContext 对象。
        /// </summary>
        public TestContext(string connectionString) : 
                base(connectionString, "TestContext")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// 初始化新的 TestContext 对象。
        /// </summary>
        public TestContext(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "TestContext")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// 架构中不存在 goods 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<goods> goods
        {
            get
            {
                if ((this._goods == null))
                {
                    this._goods = base.CreateQuery<goods>("[goods]");
                }
                return this._goods;
            }
        }
        private global::System.Data.Objects.ObjectQuery<goods> _goods;
        /// <summary>
        /// 架构中不存在 goods_type 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<goods_type> goods_type
        {
            get
            {
                if ((this._goods_type == null))
                {
                    this._goods_type = base.CreateQuery<goods_type>("[goods_type]");
                }
                return this._goods_type;
            }
        }
        private global::System.Data.Objects.ObjectQuery<goods_type> _goods_type;
        /// <summary>
        /// 架构中不存在 onhand 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<onhand> onhand
        {
            get
            {
                if ((this._onhand == null))
                {
                    this._onhand = base.CreateQuery<onhand>("[onhand]");
                }
                return this._onhand;
            }
        }
        private global::System.Data.Objects.ObjectQuery<onhand> _onhand;
        /// <summary>
        /// 架构中不存在 store 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<store> store
        {
            get
            {
                if ((this._store == null))
                {
                    this._store = base.CreateQuery<store>("[store]");
                }
                return this._store;
            }
        }
        private global::System.Data.Objects.ObjectQuery<store> _store;
        /// <summary>
        /// 架构中不存在 test_main 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<test_main> test_main
        {
            get
            {
                if ((this._test_main == null))
                {
                    this._test_main = base.CreateQuery<test_main>("[test_main]");
                }
                return this._test_main;
            }
        }
        private global::System.Data.Objects.ObjectQuery<test_main> _test_main;
        /// <summary>
        /// 架构中不存在 test_sub 的注释。
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<test_sub> test_sub
        {
            get
            {
                if ((this._test_sub == null))
                {
                    this._test_sub = base.CreateQuery<test_sub>("[test_sub]");
                }
                return this._test_sub;
            }
        }
        private global::System.Data.Objects.ObjectQuery<test_sub> _test_sub;
        /// <summary>
        /// 架构中不存在 goods 的注释。
        /// </summary>
        public void AddTogoods(goods goods)
        {
            base.AddObject("goods", goods);
        }
        /// <summary>
        /// 架构中不存在 goods_type 的注释。
        /// </summary>
        public void AddTogoods_type(goods_type goods_type)
        {
            base.AddObject("goods_type", goods_type);
        }
        /// <summary>
        /// 架构中不存在 onhand 的注释。
        /// </summary>
        public void AddToonhand(onhand onhand)
        {
            base.AddObject("onhand", onhand);
        }
        /// <summary>
        /// 架构中不存在 store 的注释。
        /// </summary>
        public void AddTostore(store store)
        {
            base.AddObject("store", store);
        }
        /// <summary>
        /// 架构中不存在 test_main 的注释。
        /// </summary>
        public void AddTotest_main(test_main test_main)
        {
            base.AddObject("test_main", test_main);
        }
        /// <summary>
        /// 架构中不存在 test_sub 的注释。
        /// </summary>
        public void AddTotest_sub(test_sub test_sub)
        {
            base.AddObject("test_sub", test_sub);
        }
    }
    /// <summary>
    /// 架构中不存在 A0610_EF.Sample.goods 的注释。
    /// </summary>
    /// <KeyProperties>
    /// goodsid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="A0610_EF.Sample", Name="goods")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class goods : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 goods 对象。
        /// </summary>
        /// <param name="goodsid">goodsid 的初始值。</param>
        /// <param name="name">name 的初始值。</param>
        public static goods Creategoods(string goodsid, string name)
        {
            goods goods = new goods();
            goods.goodsid = goodsid;
            goods.name = name;
            return goods;
        }
        /// <summary>
        /// 架构中不存在属性 goodsid 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string goodsid
        {
            get
            {
                return this._goodsid;
            }
            set
            {
                this.OngoodsidChanging(value);
                this.ReportPropertyChanging("goodsid");
                this._goodsid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("goodsid");
                this.OngoodsidChanged();
            }
        }
        private string _goodsid;
        partial void OngoodsidChanging(string value);
        partial void OngoodsidChanged();
        /// <summary>
        /// 架构中不存在属性 name 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this.ReportPropertyChanging("name");
                this._name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("name");
                this.OnnameChanged();
            }
        }
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// 架构中不存在属性 unit 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string unit
        {
            get
            {
                return this._unit;
            }
            set
            {
                this.OnunitChanging(value);
                this.ReportPropertyChanging("unit");
                this._unit = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("unit");
                this.OnunitChanged();
            }
        }
        private string _unit;
        partial void OnunitChanging(string value);
        partial void OnunitChanged();
        /// <summary>
        /// 架构中不存在属性 in_price 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> in_price
        {
            get
            {
                return this._in_price;
            }
            set
            {
                this.Onin_priceChanging(value);
                this.ReportPropertyChanging("in_price");
                this._in_price = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("in_price");
                this.Onin_priceChanged();
            }
        }
        private global::System.Nullable<decimal> _in_price;
        partial void Onin_priceChanging(global::System.Nullable<decimal> value);
        partial void Onin_priceChanged();
        /// <summary>
        /// 架构中不存在属性 out_price 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> out_price
        {
            get
            {
                return this._out_price;
            }
            set
            {
                this.Onout_priceChanging(value);
                this.ReportPropertyChanging("out_price");
                this._out_price = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("out_price");
                this.Onout_priceChanged();
            }
        }
        private global::System.Nullable<decimal> _out_price;
        partial void Onout_priceChanging(global::System.Nullable<decimal> value);
        partial void Onout_priceChanged();
        /// <summary>
        /// 架构中不存在属性 maxqty 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> maxqty
        {
            get
            {
                return this._maxqty;
            }
            set
            {
                this.OnmaxqtyChanging(value);
                this.ReportPropertyChanging("maxqty");
                this._maxqty = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("maxqty");
                this.OnmaxqtyChanged();
            }
        }
        private global::System.Nullable<decimal> _maxqty;
        partial void OnmaxqtyChanging(global::System.Nullable<decimal> value);
        partial void OnmaxqtyChanged();
        /// <summary>
        /// 架构中不存在属性 minqty 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<decimal> minqty
        {
            get
            {
                return this._minqty;
            }
            set
            {
                this.OnminqtyChanging(value);
                this.ReportPropertyChanging("minqty");
                this._minqty = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("minqty");
                this.OnminqtyChanged();
            }
        }
        private global::System.Nullable<decimal> _minqty;
        partial void OnminqtyChanging(global::System.Nullable<decimal> value);
        partial void OnminqtyChanged();
        /// <summary>
        /// 架构中不存在 goods_type 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("A0610_EF.Sample", "FK__goods__type_id__1273C1CD", "goods_type")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public goods_type goods_type
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<goods_type>("A0610_EF.Sample.FK__goods__type_id__1273C1CD", "goods_type").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<goods_type>("A0610_EF.Sample.FK__goods__type_id__1273C1CD", "goods_type").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 goods_type 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<goods_type> goods_typeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<goods_type>("A0610_EF.Sample.FK__goods__type_id__1273C1CD", "goods_type");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<goods_type>("A0610_EF.Sample.FK__goods__type_id__1273C1CD", "goods_type", value);
                }
            }
        }
        /// <summary>
        /// 架构中不存在 onhand 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("A0610_EF.Sample", "FK__onhand__goodsid__117F9D94", "onhand")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<onhand> onhand
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<onhand>("A0610_EF.Sample.FK__onhand__goodsid__117F9D94", "onhand");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<onhand>("A0610_EF.Sample.FK__onhand__goodsid__117F9D94", "onhand", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 A0610_EF.Sample.goods_type 的注释。
    /// </summary>
    /// <KeyProperties>
    /// type_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="A0610_EF.Sample", Name="goods_type")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class goods_type : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 goods_type 对象。
        /// </summary>
        /// <param name="type_id">type_id 的初始值。</param>
        /// <param name="type_code">type_code 的初始值。</param>
        /// <param name="type_name">type_name 的初始值。</param>
        public static goods_type Creategoods_type(int type_id, string type_code, string type_name)
        {
            goods_type goods_type = new goods_type();
            goods_type.type_id = type_id;
            goods_type.type_code = type_code;
            goods_type.type_name = type_name;
            return goods_type;
        }
        /// <summary>
        /// 架构中不存在属性 type_id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int type_id
        {
            get
            {
                return this._type_id;
            }
            set
            {
                this.Ontype_idChanging(value);
                this.ReportPropertyChanging("type_id");
                this._type_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("type_id");
                this.Ontype_idChanged();
            }
        }
        private int _type_id;
        partial void Ontype_idChanging(int value);
        partial void Ontype_idChanged();
        /// <summary>
        /// 架构中不存在属性 type_code 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string type_code
        {
            get
            {
                return this._type_code;
            }
            set
            {
                this.Ontype_codeChanging(value);
                this.ReportPropertyChanging("type_code");
                this._type_code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("type_code");
                this.Ontype_codeChanged();
            }
        }
        private string _type_code;
        partial void Ontype_codeChanging(string value);
        partial void Ontype_codeChanged();
        /// <summary>
        /// 架构中不存在属性 type_name 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string type_name
        {
            get
            {
                return this._type_name;
            }
            set
            {
                this.Ontype_nameChanging(value);
                this.ReportPropertyChanging("type_name");
                this._type_name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("type_name");
                this.Ontype_nameChanged();
            }
        }
        private string _type_name;
        partial void Ontype_nameChanging(string value);
        partial void Ontype_nameChanged();
        /// <summary>
        /// 架构中不存在属性 description 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// 架构中不存在 goods 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("A0610_EF.Sample", "FK__goods__type_id__1273C1CD", "goods")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<goods> goods
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<goods>("A0610_EF.Sample.FK__goods__type_id__1273C1CD", "goods");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<goods>("A0610_EF.Sample.FK__goods__type_id__1273C1CD", "goods", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 A0610_EF.Sample.onhand 的注释。
    /// </summary>
    /// <KeyProperties>
    /// store_id
    /// goodsid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="A0610_EF.Sample", Name="onhand")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class onhand : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 onhand 对象。
        /// </summary>
        /// <param name="store_id">store_id 的初始值。</param>
        /// <param name="goodsid">goodsid 的初始值。</param>
        /// <param name="onhand1">onhand1 的初始值。</param>
        public static onhand Createonhand(int store_id, string goodsid, int onhand1)
        {
            onhand onhand = new onhand();
            onhand.store_id = store_id;
            onhand.goodsid = goodsid;
            onhand.onhand1 = onhand1;
            return onhand;
        }
        /// <summary>
        /// 架构中不存在属性 store_id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int store_id
        {
            get
            {
                return this._store_id;
            }
            set
            {
                this.Onstore_idChanging(value);
                this.ReportPropertyChanging("store_id");
                this._store_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("store_id");
                this.Onstore_idChanged();
            }
        }
        private int _store_id;
        partial void Onstore_idChanging(int value);
        partial void Onstore_idChanged();
        /// <summary>
        /// 架构中不存在属性 goodsid 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string goodsid
        {
            get
            {
                return this._goodsid;
            }
            set
            {
                this.OngoodsidChanging(value);
                this.ReportPropertyChanging("goodsid");
                this._goodsid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("goodsid");
                this.OngoodsidChanged();
            }
        }
        private string _goodsid;
        partial void OngoodsidChanging(string value);
        partial void OngoodsidChanged();
        /// <summary>
        /// 架构中不存在属性 onhand1 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int onhand1
        {
            get
            {
                return this._onhand1;
            }
            set
            {
                this.Ononhand1Changing(value);
                this.ReportPropertyChanging("onhand1");
                this._onhand1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("onhand1");
                this.Ononhand1Changed();
            }
        }
        private int _onhand1;
        partial void Ononhand1Changing(int value);
        partial void Ononhand1Changed();
        /// <summary>
        /// 架构中不存在 goods 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("A0610_EF.Sample", "FK__onhand__goodsid__117F9D94", "goods")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public goods goods
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<goods>("A0610_EF.Sample.FK__onhand__goodsid__117F9D94", "goods").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<goods>("A0610_EF.Sample.FK__onhand__goodsid__117F9D94", "goods").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 goods 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<goods> goodsReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<goods>("A0610_EF.Sample.FK__onhand__goodsid__117F9D94", "goods");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<goods>("A0610_EF.Sample.FK__onhand__goodsid__117F9D94", "goods", value);
                }
            }
        }
        /// <summary>
        /// 架构中不存在 store 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("A0610_EF.Sample", "FK__onhand__store_id__1367E606", "store")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public store store
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<store>("A0610_EF.Sample.FK__onhand__store_id__1367E606", "store").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<store>("A0610_EF.Sample.FK__onhand__store_id__1367E606", "store").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 store 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<store> storeReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<store>("A0610_EF.Sample.FK__onhand__store_id__1367E606", "store");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<store>("A0610_EF.Sample.FK__onhand__store_id__1367E606", "store", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 A0610_EF.Sample.store 的注释。
    /// </summary>
    /// <KeyProperties>
    /// store_id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="A0610_EF.Sample", Name="store")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class store : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 store 对象。
        /// </summary>
        /// <param name="store_id">store_id 的初始值。</param>
        /// <param name="store_code">store_code 的初始值。</param>
        /// <param name="store_name">store_name 的初始值。</param>
        public static store Createstore(int store_id, string store_code, string store_name)
        {
            store store = new store();
            store.store_id = store_id;
            store.store_code = store_code;
            store.store_name = store_name;
            return store;
        }
        /// <summary>
        /// 架构中不存在属性 store_id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int store_id
        {
            get
            {
                return this._store_id;
            }
            set
            {
                this.Onstore_idChanging(value);
                this.ReportPropertyChanging("store_id");
                this._store_id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("store_id");
                this.Onstore_idChanged();
            }
        }
        private int _store_id;
        partial void Onstore_idChanging(int value);
        partial void Onstore_idChanged();
        /// <summary>
        /// 架构中不存在属性 store_code 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string store_code
        {
            get
            {
                return this._store_code;
            }
            set
            {
                this.Onstore_codeChanging(value);
                this.ReportPropertyChanging("store_code");
                this._store_code = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("store_code");
                this.Onstore_codeChanged();
            }
        }
        private string _store_code;
        partial void Onstore_codeChanging(string value);
        partial void Onstore_codeChanged();
        /// <summary>
        /// 架构中不存在属性 store_name 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string store_name
        {
            get
            {
                return this._store_name;
            }
            set
            {
                this.Onstore_nameChanging(value);
                this.ReportPropertyChanging("store_name");
                this._store_name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("store_name");
                this.Onstore_nameChanged();
            }
        }
        private string _store_name;
        partial void Onstore_nameChanging(string value);
        partial void Onstore_nameChanged();
        /// <summary>
        /// 架构中不存在属性 description 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// 架构中不存在 onhand 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("A0610_EF.Sample", "FK__onhand__store_id__1367E606", "onhand")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<onhand> onhand
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<onhand>("A0610_EF.Sample.FK__onhand__store_id__1367E606", "onhand");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<onhand>("A0610_EF.Sample.FK__onhand__store_id__1367E606", "onhand", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 A0610_EF.Sample.test_main 的注释。
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="A0610_EF.Sample", Name="test_main")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class test_main : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 test_main 对象。
        /// </summary>
        /// <param name="id">id 的初始值。</param>
        public static test_main Createtest_main(int id)
        {
            test_main test_main = new test_main();
            test_main.id = id;
            return test_main;
        }
        /// <summary>
        /// 架构中不存在属性 id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// 架构中不存在属性 value 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string value
        {
            get
            {
                return this._value;
            }
            set
            {
                this.OnvalueChanging(value);
                this.ReportPropertyChanging("value");
                this._value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("value");
                this.OnvalueChanged();
            }
        }
        private string _value;
        partial void OnvalueChanging(string value);
        partial void OnvalueChanged();
        /// <summary>
        /// 架构中不存在 test_sub 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("A0610_EF.Sample", "main_id_cons", "test_sub")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<test_sub> test_sub
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<test_sub>("A0610_EF.Sample.main_id_cons", "test_sub");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<test_sub>("A0610_EF.Sample.main_id_cons", "test_sub", value);
                }
            }
        }
    }
    /// <summary>
    /// 架构中不存在 A0610_EF.Sample.test_sub 的注释。
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="A0610_EF.Sample", Name="test_sub")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class test_sub : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// 创建新的 test_sub 对象。
        /// </summary>
        /// <param name="id">id 的初始值。</param>
        public static test_sub Createtest_sub(int id)
        {
            test_sub test_sub = new test_sub();
            test_sub.id = id;
            return test_sub;
        }
        /// <summary>
        /// 架构中不存在属性 id 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this.ReportPropertyChanging("id");
                this._id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id");
                this.OnidChanged();
            }
        }
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// 架构中不存在属性 value 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string value
        {
            get
            {
                return this._value;
            }
            set
            {
                this.OnvalueChanging(value);
                this.ReportPropertyChanging("value");
                this._value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("value");
                this.OnvalueChanged();
            }
        }
        private string _value;
        partial void OnvalueChanging(string value);
        partial void OnvalueChanged();
        /// <summary>
        /// 架构中不存在 test_main 的注释。
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("A0610_EF.Sample", "main_id_cons", "test_main")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public test_main test_main
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<test_main>("A0610_EF.Sample.main_id_cons", "test_main").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<test_main>("A0610_EF.Sample.main_id_cons", "test_main").Value = value;
            }
        }
        /// <summary>
        /// 架构中不存在 test_main 的注释。
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<test_main> test_mainReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<test_main>("A0610_EF.Sample.main_id_cons", "test_main");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<test_main>("A0610_EF.Sample.main_id_cons", "test_main", value);
                }
            }
        }
    }
}
