/*
CREATED		2012/8/14
MODIFIED		2012/8/15
PROJECT		
MODEL		
COMPANY		
AUTHOR		
VERSION		
DATABASE		ORACLE 9I 
*/









ALTER TABLE "MR_DEPT" DROP CONSTRAINT "FK_MR_DEPT_T"
/
ALTER TABLE "MR_DEPT_USER" DROP CONSTRAINT "FK_MR_DEPT_USER_D"
/
ALTER TABLE "MR_DEPT_USER" DROP CONSTRAINT "FK_MR_DEPT_USER_U"
/
ALTER TABLE "MR_USER_MODULE" DROP CONSTRAINT "FK_MR_USER_MODULE_U"
/
ALTER TABLE "MR_USER_ACTION" DROP CONSTRAINT "FK_MR_USER_ACTION_U"
/
ALTER TABLE "MR_USER_ROLE" DROP CONSTRAINT "FK_MR_USER_ROLE_U"
/
ALTER TABLE "MR_ACTION" DROP CONSTRAINT "FK_MR_ACTION_M"
/
ALTER TABLE "MR_USER_MODULE" DROP CONSTRAINT "FK_MR_USER_MODULE_M"
/
ALTER TABLE "MR_ROLE_MODULE" DROP CONSTRAINT "FK_MR_ROLE_MODULE_M"
/
ALTER TABLE "MR_USER_ACTION" DROP CONSTRAINT "FK_MR_USER_ACTION_A"
/
ALTER TABLE "MR_ROLE_ACTION" DROP CONSTRAINT "FK_MR_ROLE_ACTION_A"
/
ALTER TABLE "MR_USER_ROLE" DROP CONSTRAINT "FK_MR_USER_ROLE_R"
/
ALTER TABLE "MR_ROLE_MODULE" DROP CONSTRAINT "FK_MR_ROLE_MODULE_R"
/
ALTER TABLE "MR_ROLE_ACTION" DROP CONSTRAINT "FK_MR_ROLE_ACTION_R"
/



DROP TABLE "MR_ROLE_ACTION"
/
DROP TABLE "MR_ROLE_MODULE"
/
DROP TABLE "MR_USER_ROLE"
/
DROP TABLE "MR_ROLE"
/
DROP TABLE "MR_USER_ACTION"
/
DROP TABLE "MR_USER_MODULE"
/
DROP TABLE "MR_ACTION"
/
DROP TABLE "MR_MODULE"
/
DROP TABLE "MR_DEPT_USER"
/
DROP TABLE "MR_USER"
/
DROP TABLE "MR_DEPT"
/
DROP TABLE "MR_DEPT_TYPE"
/


-- CREATE TYPES SECTION





-- CREATE TABLES SECTION


CREATE TABLE "MR_DEPT_TYPE" (
	"DEPT_TYPE" VARCHAR2 (20) NOT NULL ,
	"DEPT_TYPE_DESC" VARCHAR2 (100) NOT NULL ,
	"STATUS" SMALLINT DEFAULT 1 NOT NULL ,
 CONSTRAINT "PK_MR_DEPT_TYPE" PRIMARY KEY ("DEPT_TYPE") 
) 
/

CREATE TABLE "MR_DEPT" (
	"DEPT_CODE" VARCHAR2 (20) NOT NULL ,
	"DEPT_TYPE" VARCHAR2 (20) NOT NULL ,
	"PARENT_CODE" VARCHAR2 (20),
	"DEPT_NAME" VARCHAR2 (20) NOT NULL ,
	"STATUS" SMALLINT DEFAULT 1 NOT NULL ,
 CONSTRAINT "PK_MR_DEPT" PRIMARY KEY ("DEPT_CODE") 
) 
/

CREATE TABLE "MR_USER" (
	"USER_CODE" VARCHAR2 (20) NOT NULL ,
	"USER_NAME" VARCHAR2 (20) NOT NULL ,
	"STATUS" SMALLINT DEFAULT 1 NOT NULL ,
 CONSTRAINT "PK_MR_USER" PRIMARY KEY ("USER_CODE") 
) 
/

CREATE TABLE "MR_DEPT_USER" (
	"DEPT_CODE" VARCHAR2 (20) NOT NULL ,
	"USER_CODE" VARCHAR2 (20) NOT NULL ,
 CONSTRAINT "PK_MR_DEPT_USER" PRIMARY KEY ("DEPT_CODE","USER_CODE") 
) 
/

CREATE TABLE "MR_MODULE" (
	"MODULE_CODE" VARCHAR2 (20) NOT NULL ,
	"PARENT_CODE" VARCHAR2 (20),
	"MODULE_NAME" VARCHAR2 (20) NOT NULL ,
	"MODULE_EXPAND" VARCHAR2 (100),
	"STATUS" SMALLINT DEFAULT 1 NOT NULL ,
 CONSTRAINT "PK_MR_MODULE" PRIMARY KEY ("MODULE_CODE") 
) 
/

CREATE TABLE "MR_ACTION" (
	"ACTION_CODE" VARCHAR2 (20) NOT NULL ,
	"MODULE_CODE" VARCHAR2 (20) NOT NULL ,
	"ACTION_NAME" VARCHAR2 (20) NOT NULL ,
	"ACTION_EXPAND" VARCHAR2 (100),
	"DEFAULT_RULE" SMALLINT DEFAULT 0 NOT NULL ,
	"STATUS" SMALLINT DEFAULT 1 NOT NULL ,
 CONSTRAINT "PK_MR_ACTION" PRIMARY KEY ("ACTION_CODE") 
) 
/

CREATE TABLE "MR_USER_MODULE" (
	"USER_CODE" VARCHAR2 (20) NOT NULL ,
	"MODULE_CODE" VARCHAR2 (20) NOT NULL ,
 CONSTRAINT "PK_MR_USER_MODULE" PRIMARY KEY ("USER_CODE","MODULE_CODE") 
) 
/

CREATE TABLE "MR_USER_ACTION" (
	"USER_CODE" VARCHAR2 (20) NOT NULL ,
	"ACTION_CODE" VARCHAR2 (20) NOT NULL ,
 CONSTRAINT "PK_MR_USER_ACTION" PRIMARY KEY ("USER_CODE","ACTION_CODE") 
) 
/

CREATE TABLE "MR_ROLE" (
	"ROLE_CODE" VARCHAR2 (20) NOT NULL ,
	"ROLE_NAME" VARCHAR2 (20) NOT NULL ,
	"STATUS" SMALLINT DEFAULT 1 NOT NULL ,
 CONSTRAINT "PK_MR_ROLE" PRIMARY KEY ("ROLE_CODE") 
) 
/

CREATE TABLE "MR_USER_ROLE" (
	"USER_CODE" VARCHAR2 (20) NOT NULL ,
	"ROLE_CODE" VARCHAR2 (20) NOT NULL ,
 CONSTRAINT "PK_MR_USER_ROLE" PRIMARY KEY ("USER_CODE","ROLE_CODE") 
) 
/

CREATE TABLE "MR_ROLE_MODULE" (
	"MODULE_CODE" VARCHAR2 (20) NOT NULL ,
	"ROLE_CODE" VARCHAR2 (20) NOT NULL ,
 CONSTRAINT "PK_MR_ROLE_MODULE" PRIMARY KEY ("MODULE_CODE","ROLE_CODE") 
) 
/

CREATE TABLE "MR_ROLE_ACTION" (
	"ROLE_CODE" VARCHAR2 (20) NOT NULL ,
	"ACTION_CODE" VARCHAR2 (20) NOT NULL ,
 CONSTRAINT "PK_MR_ROLE_ACTION" PRIMARY KEY ("ROLE_CODE","ACTION_CODE") 
) 
/



--------------------------------------------------------------------------------
-- 部门表的父子关系
--------------------------------------------------------------------------------

ALTER TABLE MR_DEPT ADD CONSTRAINT FK_MR_DEPT_PARENT  FOREIGN KEY (PARENT_CODE)  REFERENCES  MR_DEPT
/
--------------------------------------------------------------------------------
-- 功能模块表的父子关系
--------------------------------------------------------------------------------

ALTER TABLE MR_MODULE ADD CONSTRAINT FK_MR_MODULE_PARENT  FOREIGN KEY (PARENT_CODE)  REFERENCES  MR_MODULE
/



-- CREATE INDEXES SECTION



-- CREATE SECTION FOR PKS, AKS AND UNIQUE CONSTRAINTS, WHICH HAVE TO BE GENERATED AFTER INDEXES



-- CREATE FOREIGN KEYS SECTION

ALTER TABLE "MR_DEPT" ADD CONSTRAINT "FK_MR_DEPT_T" FOREIGN KEY ("DEPT_TYPE") REFERENCES "MR_DEPT_TYPE" ("DEPT_TYPE") 
/

ALTER TABLE "MR_DEPT_USER" ADD CONSTRAINT "FK_MR_DEPT_USER_D" FOREIGN KEY ("DEPT_CODE") REFERENCES "MR_DEPT" ("DEPT_CODE") 
/

ALTER TABLE "MR_DEPT_USER" ADD CONSTRAINT "FK_MR_DEPT_USER_U" FOREIGN KEY ("USER_CODE") REFERENCES "MR_USER" ("USER_CODE") 
/

ALTER TABLE "MR_USER_MODULE" ADD CONSTRAINT "FK_MR_USER_MODULE_U" FOREIGN KEY ("USER_CODE") REFERENCES "MR_USER" ("USER_CODE") 
/

ALTER TABLE "MR_USER_ACTION" ADD CONSTRAINT "FK_MR_USER_ACTION_U" FOREIGN KEY ("USER_CODE") REFERENCES "MR_USER" ("USER_CODE") 
/

ALTER TABLE "MR_USER_ROLE" ADD CONSTRAINT "FK_MR_USER_ROLE_U" FOREIGN KEY ("USER_CODE") REFERENCES "MR_USER" ("USER_CODE") 
/

ALTER TABLE "MR_ACTION" ADD CONSTRAINT "FK_MR_ACTION_M" FOREIGN KEY ("MODULE_CODE") REFERENCES "MR_MODULE" ("MODULE_CODE") 
/

ALTER TABLE "MR_USER_MODULE" ADD CONSTRAINT "FK_MR_USER_MODULE_M" FOREIGN KEY ("MODULE_CODE") REFERENCES "MR_MODULE" ("MODULE_CODE") 
/

ALTER TABLE "MR_ROLE_MODULE" ADD CONSTRAINT "FK_MR_ROLE_MODULE_M" FOREIGN KEY ("MODULE_CODE") REFERENCES "MR_MODULE" ("MODULE_CODE") 
/

ALTER TABLE "MR_USER_ACTION" ADD CONSTRAINT "FK_MR_USER_ACTION_A" FOREIGN KEY ("ACTION_CODE") REFERENCES "MR_ACTION" ("ACTION_CODE") 
/

ALTER TABLE "MR_ROLE_ACTION" ADD CONSTRAINT "FK_MR_ROLE_ACTION_A" FOREIGN KEY ("ACTION_CODE") REFERENCES "MR_ACTION" ("ACTION_CODE") 
/

ALTER TABLE "MR_USER_ROLE" ADD CONSTRAINT "FK_MR_USER_ROLE_R" FOREIGN KEY ("ROLE_CODE") REFERENCES "MR_ROLE" ("ROLE_CODE") 
/

ALTER TABLE "MR_ROLE_MODULE" ADD CONSTRAINT "FK_MR_ROLE_MODULE_R" FOREIGN KEY ("ROLE_CODE") REFERENCES "MR_ROLE" ("ROLE_CODE") 
/

ALTER TABLE "MR_ROLE_ACTION" ADD CONSTRAINT "FK_MR_ROLE_ACTION_R" FOREIGN KEY ("ROLE_CODE") REFERENCES "MR_ROLE" ("ROLE_CODE") 
/


-- CREATE OBJECT TABLES SECTION



-- CREATE XMLTYPE TABLES SECTION



-- CREATE FUNCTIONS SECTION



-- CREATE SEQUENCES SECTION




-- CREATE PACKAGES SECTION





-- CREATE SYNONYMS SECTION



-- CREATE TABLE COMMENTS SECTION

COMMENT ON TABLE "MR_DEPT_TYPE" IS '部门类型'
/
COMMENT ON TABLE "MR_DEPT" IS 'MR_DEPT'
/
COMMENT ON TABLE "MR_USER" IS '用户'
/
COMMENT ON TABLE "MR_DEPT_USER" IS '部门-用户关系'
/
COMMENT ON TABLE "MR_MODULE" IS '功能模块'
/
COMMENT ON TABLE "MR_ACTION" IS '模块动作'
/
COMMENT ON TABLE "MR_USER_MODULE" IS '用户-模块关系'
/
COMMENT ON TABLE "MR_USER_ACTION" IS '用户-动作关系'
/
COMMENT ON TABLE "MR_ROLE" IS '角色'
/
COMMENT ON TABLE "MR_USER_ROLE" IS '用户-角色关系'
/
COMMENT ON TABLE "MR_ROLE_MODULE" IS '角色-模块关系'
/
COMMENT ON TABLE "MR_ROLE_ACTION" IS '角色-动作关系'
/

-- CREATE ATTRIBUTE COMMENTS SECTION

COMMENT ON COLUMN "MR_DEPT_TYPE"."DEPT_TYPE" IS '部门类型'
/
COMMENT ON COLUMN "MR_DEPT_TYPE"."DEPT_TYPE_DESC" IS '部门类型描述'
/
COMMENT ON COLUMN "MR_DEPT_TYPE"."STATUS" IS '状态'
/
COMMENT ON COLUMN "MR_DEPT"."DEPT_CODE" IS '部门编号'
/
COMMENT ON COLUMN "MR_DEPT"."DEPT_TYPE" IS '部门类型(实体部门、虚拟部门、城市等)'
/
COMMENT ON COLUMN "MR_DEPT"."PARENT_CODE" IS '上级部门编号'
/
COMMENT ON COLUMN "MR_DEPT"."DEPT_NAME" IS '部门名'
/
COMMENT ON COLUMN "MR_DEPT"."STATUS" IS '状态'
/
COMMENT ON COLUMN "MR_USER"."USER_CODE" IS '用户代码'
/
COMMENT ON COLUMN "MR_USER"."USER_NAME" IS '用户名'
/
COMMENT ON COLUMN "MR_USER"."STATUS" IS '状态'
/
COMMENT ON COLUMN "MR_DEPT_USER"."DEPT_CODE" IS '部门编号'
/
COMMENT ON COLUMN "MR_DEPT_USER"."USER_CODE" IS '用户代码'
/
COMMENT ON COLUMN "MR_MODULE"."MODULE_CODE" IS '模块编号'
/
COMMENT ON COLUMN "MR_MODULE"."PARENT_CODE" IS '父模块编号'
/
COMMENT ON COLUMN "MR_MODULE"."MODULE_NAME" IS '模块名称'
/
COMMENT ON COLUMN "MR_MODULE"."MODULE_EXPAND" IS '模块扩展信息'
/
COMMENT ON COLUMN "MR_MODULE"."STATUS" IS '状态'
/
COMMENT ON COLUMN "MR_ACTION"."ACTION_CODE" IS '动作代码'
/
COMMENT ON COLUMN "MR_ACTION"."MODULE_CODE" IS '模块编号'
/
COMMENT ON COLUMN "MR_ACTION"."ACTION_NAME" IS '动作名称'
/
COMMENT ON COLUMN "MR_ACTION"."ACTION_EXPAND" IS '动作扩展信息'
/
COMMENT ON COLUMN "MR_ACTION"."DEFAULT_RULE" IS '默认可用标志'
/
COMMENT ON COLUMN "MR_ACTION"."STATUS" IS '状态'
/
COMMENT ON COLUMN "MR_USER_MODULE"."USER_CODE" IS '用户代码'
/
COMMENT ON COLUMN "MR_USER_MODULE"."MODULE_CODE" IS '模块代码'
/
COMMENT ON COLUMN "MR_USER_ACTION"."USER_CODE" IS '用户代码'
/
COMMENT ON COLUMN "MR_USER_ACTION"."ACTION_CODE" IS '动作代码'
/
COMMENT ON COLUMN "MR_ROLE"."ROLE_CODE" IS '角色代码'
/
COMMENT ON COLUMN "MR_ROLE"."ROLE_NAME" IS '角色名称'
/
COMMENT ON COLUMN "MR_ROLE"."STATUS" IS '状态'
/
COMMENT ON COLUMN "MR_USER_ROLE"."USER_CODE" IS '用户代码'
/
COMMENT ON COLUMN "MR_USER_ROLE"."ROLE_CODE" IS '角色代码'
/
COMMENT ON COLUMN "MR_ROLE_MODULE"."MODULE_CODE" IS '模块编号'
/
COMMENT ON COLUMN "MR_ROLE_MODULE"."ROLE_CODE" IS '角色代码'
/
COMMENT ON COLUMN "MR_ROLE_ACTION"."ROLE_CODE" IS '角色代码'
/
COMMENT ON COLUMN "MR_ROLE_ACTION"."ACTION_CODE" IS '动作代码'
/


