//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("Model", "MAIN_ID_CONS", "TEST_MAIN", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(MyWcfServiceLibrary.TEST_MAIN), "TEST_SUB", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyWcfServiceLibrary.TEST_SUB), true)]

#endregion

namespace MyWcfServiceLibrary
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class TestEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“TestEntities”部分中的连接字符串初始化新 TestEntities 对象。
        /// </summary>
        public TestEntities() : base("name=TestEntities", "TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 TestEntities 对象。
        /// </summary>
        public TestEntities(string connectionString) : base(connectionString, "TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 TestEntities 对象。
        /// </summary>
        public TestEntities(EntityConnection connection) : base(connection, "TestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TEST_MAIN> TEST_MAIN
        {
            get
            {
                if ((_TEST_MAIN == null))
                {
                    _TEST_MAIN = base.CreateObjectSet<TEST_MAIN>("TEST_MAIN");
                }
                return _TEST_MAIN;
            }
        }
        private ObjectSet<TEST_MAIN> _TEST_MAIN;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TEST_SUB> TEST_SUB
        {
            get
            {
                if ((_TEST_SUB == null))
                {
                    _TEST_SUB = base.CreateObjectSet<TEST_SUB>("TEST_SUB");
                }
                return _TEST_SUB;
            }
        }
        private ObjectSet<TEST_SUB> _TEST_SUB;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 TEST_MAIN EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTEST_MAIN(TEST_MAIN tEST_MAIN)
        {
            base.AddObject("TEST_MAIN", tEST_MAIN);
        }
    
        /// <summary>
        /// 用于向 TEST_SUB EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTEST_SUB(TEST_SUB tEST_SUB)
        {
            base.AddObject("TEST_SUB", tEST_SUB);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="TEST_MAIN")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TEST_MAIN : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TEST_MAIN 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static TEST_MAIN CreateTEST_MAIN(global::System.Decimal id)
        {
            TEST_MAIN tEST_MAIN = new TEST_MAIN();
            tEST_MAIN.ID = id;
            return tEST_MAIN;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VALUE
        {
            get
            {
                return _VALUE;
            }
            set
            {
                OnVALUEChanging(value);
                ReportPropertyChanging("VALUE");
                _VALUE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VALUE");
                OnVALUEChanged();
            }
        }
        private global::System.String _VALUE;
        partial void OnVALUEChanging(global::System.String value);
        partial void OnVALUEChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "MAIN_ID_CONS", "TEST_SUB")]
        public EntityCollection<TEST_SUB> TEST_SUB
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TEST_SUB>("Model.MAIN_ID_CONS", "TEST_SUB");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TEST_SUB>("Model.MAIN_ID_CONS", "TEST_SUB", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="TEST_SUB")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TEST_SUB : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TEST_SUB 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        public static TEST_SUB CreateTEST_SUB(global::System.Decimal id)
        {
            TEST_SUB tEST_SUB = new TEST_SUB();
            tEST_SUB.ID = id;
            return tEST_SUB;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Decimal _ID;
        partial void OnIDChanging(global::System.Decimal value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MAIN_ID
        {
            get
            {
                return _MAIN_ID;
            }
            set
            {
                OnMAIN_IDChanging(value);
                ReportPropertyChanging("MAIN_ID");
                _MAIN_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MAIN_ID");
                OnMAIN_IDChanged();
            }
        }
        private Nullable<global::System.Decimal> _MAIN_ID;
        partial void OnMAIN_IDChanging(Nullable<global::System.Decimal> value);
        partial void OnMAIN_IDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VALUE
        {
            get
            {
                return _VALUE;
            }
            set
            {
                OnVALUEChanging(value);
                ReportPropertyChanging("VALUE");
                _VALUE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VALUE");
                OnVALUEChanged();
            }
        }
        private global::System.String _VALUE;
        partial void OnVALUEChanging(global::System.String value);
        partial void OnVALUEChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "MAIN_ID_CONS", "TEST_MAIN")]
        public TEST_MAIN TEST_MAIN
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TEST_MAIN>("Model.MAIN_ID_CONS", "TEST_MAIN").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TEST_MAIN>("Model.MAIN_ID_CONS", "TEST_MAIN").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TEST_MAIN> TEST_MAINReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TEST_MAIN>("Model.MAIN_ID_CONS", "TEST_MAIN");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TEST_MAIN>("Model.MAIN_ID_CONS", "TEST_MAIN", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
